### ISSUE TITLE
wrong SHA?

### ISSUE THREAD

**Issue by firien** [TabbyML/homebrew-tabby#2]
> curl -L https://github.com/TabbyML/tabby/releases/download/v0.2.2/tabby_aarch64-apple-darwin | shasum -a 256

yields `43ba416ad17da09bf44b00b6aacdfceb79edf514d2ea9d6cd5bae3eeec472028`

https://github.com/TabbyML/homebrew-tabby/blob/7f5070a215824ee3c9e69e788025f0d322212253/Formula/tabby.rb#L9

**Comment by firien** [comment]
> echo -n '' | shasum -a 256

yields `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

**Comment by wsxiaoys** [comment]
Thanks for the fix!
